GET http://127.0.0.1:8000

### Get All
GET http://127.0.0.1:8000/article

{
    "page": 1,
    "limit": 10
}

### Create
POST http://127.0.0.1:8000/article
Content-Type: application/json

{
    "title": "test edit",
    "content": "Article 2 content",
    "category": "category 2",
    "status": "Publish"
}

### Get By ID
GET http://127.0.0.1:8000/article/4

### Update
PATCH http://127.0.0.1:8000/article/4
Content-Type: application/json

{
    "title": "Article 4",
    "content": "Article 4 content",
    "category": "category 1",
    "status": "Draft"
}

### Delete
DELETE http://127.0.0.1:8000/article/5
